#!/bin/bash
if npm run lint; then
    echo "Sucessfully passed linter"
else
    echo "Failed linter"
fi

if npm run deploy ; then
    echo "Sucessfully deployed"
else
    echo "Failed to deploy check the logs"
fi
