#!/bin/bash
if yarn lint; then
    echo "Sucessfully passed linter"
else
    echo "Failed linter"
    exit 1
fi

if yarn deploy ; then
    echo "Sucessfully deployed"
else
    echo "Failed to deploy check the logs"
    exit 1
fi

if yarn documentationjs ; then
    echo "Sucessfully deployed"
else
    echo "Failed to deploy check the logs"
    exit 1
fi
