#!/bin/bash
if yarn lint; then
    echo "Sucessfully passed linter"
else
    echo "Failed linter. Please try with `yarn format`"
    exit 1
fi

if yarn deploy ; then
    echo "Sucessfully deployed"
else
    echo "Failed to deploy check the logs"
    exit 1
fi


if yarn cypress:run ; then
    echo "Sucessfully ran browser tests"
else
    echo "Failed browser tests check the logs"
    exit 1
fi
